### ISSUE TITLE
How do I install the custom galaxy/cloudman Nginx RPM?

### ISSUE THREAD

**Issue by MatthewRalston** [galaxyproject/galaxy-cloudman-playbook#12]
Hello, after running ```build/nginx.yml``` in CentOS, I am left with an rpm file. After installing the rpm, I have attempted to start the nginx service

```
>service nginx start
nginx: unrecognized service
```

How can I install this rpm so that I can restart nginx with appropriate configurations?
Tasks:
```
- name: Create work dir
  file: path={{ work_dir }} state=directory

- name: Update APT cache
  apt: update_cache=yes cache_valid_time=3600
  sudo: True
  when: ansible_distribution == "Ubuntu"

- name: Install prerequisite packages for Ubuntu
  apt: name={{ item }} state=latest
  with_items:
    - make
    - ruby
    - ruby-dev
    - git
    - libpam-dev
    - libssl-dev
  sudo: True
  when: ansible_os_family == "Debian"

- name: Install prerequisite packages  for CentOS
  yum: name={{ item }} state=latest
  with_items:
    - git
    - make
    - openssl-devel
    - pam      
    - pam-devel
    - pam_ldap
    - ruby-devel
    - rubygems
  sudo: True
  when: ansible_distribution == "CentOS"

    
- name: Install prerequisite packages specific to Ubuntu 12.04
  apt: name={{ item }} state=latest
  with_items:
    - rubygems
  sudo: True
  when: ansible_distribution_release == "Precise"

- name: Install fpm
  gem: name=fpm state=present user_install=no
  sudo: True

- name: Fetch nginx source
  get_url:
    url=http://nginx.org/download/nginx-{{ nginx_version }}.tar.gz
    sha256sum={{ nginx_sha256 }}
    dest={{ work_dir }}/nginx-{{ nginx_version }}.tar.gz

- name: Untar nginx source
  unarchive: src={{ work_dir }}/nginx-{{ nginx_version }}.tar.gz
    dest={{ work_dir }} copy=no creates={{ work_dir }}/nginx-{{ nginx_version }}

- name: Fetch nginx_upload_module source
  git: repo={{ nginx_upload_module_repo }}
    version={{ nginx_upload_module_branch }} dest={{ work_dir }}/nginx_upload_module

- name: Fetch nginx_http_auth_pam_module source
  get_url: url=http://web.iti.upv.es/~sto/nginx/ngx_http_auth_pam_module-{{ nginx_http_auth_pam_module_version }}.tar.gz
    sha256sum={{ nginx_http_auth_pam_module_sha256 }} dest={{ work_dir }}/ngx_http_auth_pam_module-{{ nginx_http_auth_pam_module_version }}.tar.gz

- name: Untar nginx_http_auth_pam_module source
  unarchive: src={{ work_dir }}/ngx_http_auth_pam_module-{{ nginx_http_auth_pam_module_version }}.tar.gz
    dest={{ work_dir }} copy=no creates={{ work_dir }}/ngx_http_auth_pam_module-{{ nginx_http_auth_pam_module_version }}

- name: Fetch PCRE source
  get_url: url=ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre-{{ pcre_version }}.tar.gz
    sha256sum={{ pcre_sha256 }} dest={{ work_dir }}/pcre-{{ pcre_version }}.tar.gz
  when: ansible_distribution == "CHANGEME"

- name: Untar PCRE source
  unarchive: src={{ work_dir}}/pcre-{{ pcre_version }}.tar.gz
    dest={{ work_dir }} copy=no creates={{ work_dir }}/pcre-{{ pcre_version }}

- name: Fetch zlib source
  get_url: url=http://zlib.net/zlib-{{ zlib_version }}.tar.gz
    sha256sum={{ zlib_sha256 }} dest={{ work_dir }}/zlib-{{ zlib_version }}.tar.gz

- name: Untar zlib source
  unarchive: src={{ work_dir }}/zlib-{{ zlib_version }}.tar.gz
    dest={{ work_dir }} copy=no creates={{ work_dir }}/zlib-{{ zlib_version }}

- name: Configure nginx
  command: ./configure {{ nginx_configure_args }}
    chdir={{ work_dir }}/nginx-{{ nginx_version }}
    creates={{ work_dir }}/nginx-{{ nginx_version }}/objs/ngx_auto_config.h

- name: Build nginx
  command: make
    chdir={{ work_dir }}/nginx-{{ nginx_version }}
    creates={{ work_dir }}/nginx-{{ nginx_version }}/objs/nginx

- name: Stage nginx package
  command: make DESTDIR={{ work_dir }}/nginx-{{ nginx_version }}-dest INSTALL_USER={{ user_id }} INSTALL_GROUP={{ user_group }} install
    chdir={{ work_dir }}/nginx-{{ nginx_version }}
    creates={{ work_dir }}/nginx-{{ nginx_version }}-dest

- name: Create var-opt dir
  command: mkdir -p {{ work_dir }}/nginx-{{ nginx_version }}-dest/{{ var_opt_path }}/nginx

- name: Create RPM
  command: fpm -s dir -t rpm -n galaxy-nginx -v {{ nginx_version }}-{{ build_id }}.gxy -p {{ work_dir }}/galaxy-nginx-{{ nginx_version }}_gxy{{ build_id }}_x86_64.rpm {{ fpm_args }} {{ nginx_dir_prefix | regex_replace('^/(\w+)/.*$', '\\1') }} var
    chdir={{ work_dir }}/nginx-{{ nginx_version }}-dest
    creates={{ work_dir }}/{{ work_dir }}/galaxy-nginx-{{ nginx_version }}_gxy{{ build_id }}_x86_64.rpm
  when: ansible_os_family == "CentOS"

- name: Create deb
  command: fpm -s dir -t deb -n galaxy-nginx -v {{ nginx_version }}-gxy{{ build_id }}-{{ ansible_lsb['codename'] }} -p {{ work_dir }}/galaxy-nginx-{{ nginx_version }}_gxy{{ build_id }}-{{ ansible_lsb['codename'] }}_amd64.deb {{ fpm_args }} --conflicts nginx --conflicts nginx-core --conflicts nginx-common {{ nginx_dir_prefix | regex_replace('^/(\w+)/.*$', '\\1') }} var
    chdir={{ work_dir }}/nginx-{{ nginx_version }}-dest
    creates={{ work_dir }}/galaxy-nginx-{{ nginx_version }}_gxy{{ build_id }}-{{ ansible_lsb['codename'] }}_amd64.deb
  when: ansible_os_family == "Debian"

- name: Install Nginx RPM
  command: rpm -Uvh {{ work_dir }}/galaxy-nginx-{{ nginx_version }}_gxy{{ build_id }}_x86_64.rpm
  when: ansible_distribution == "CentOS"
```
